# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Macedo-Romanian spellchecker"
rup = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Macedo-Romanian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
rup = "TRANSLATE: A spellchecker for Macedo-Romanian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.rup"

[windows]
system_product_code = "{D4FFF3F0-E8E2-4DCE-BB52-397F8ACA5AB1}_is1"
legacy_product_codes = [
    { value = "B6FD06A8-2448-4A35-AF3F-698D82DA6777", kind = "nsis" },
    { value = "6C450BEB-4EB7-49F6-99ED-0B46CA269E6B", kind = "nsis" }
]

[package.speller]
name = "Macedo-Romanian"
version = "0.1.1"

[package.grammar]
name = "Macedo-Romanian"
version = "0.1.0"

[package.tts-textproc]
name = "Macedo-Romanian"
version = "0.1.0"

[package.hyphenator]
name = "Macedo-Romanian"
version = "0.1.0"
