template = "https://github.com/giellalt/template-lang-und"
rev_id = 274
template_sha = "43a0f0c0afaa856365e2bf3d3cb7eae06d27cc4d"

[replacements]
__GLOTTOLOG_ID__ = "arom1237"
__REPO__ = "lang-rup"
__UND2C__ = "rup"
__UNDEFINED__ = "Macedo-Romanian"
__UND__ = "rup"
