template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "arom1237"
__REPO__ = "lang-rup"
__UND2C__ = "rup"
__UNDEFINED__ = "Macedo-Romanian"
__UND__ = "rup"
